# Generated by Django 2.2.10 on 2021-09-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_poll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
