# Generated by Django 2.2.10 on 2021-09-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answertext',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Choice'), (3, 'Multiple choice')], default=1),
        ),
        migrations.DeleteModel(
            name='AnswerChoice',
        ),
        migrations.DeleteModel(
            name='AnswerText',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='polls.Question'),
        ),
    ]
