version: "3"

services:
  db:
    restart: unless-stopped
    image: postgres:11
    volumes:
      - database_volume:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env
  backend:
    restart: unless-stopped
    build: ./backend
    volumes:
      - ./backend:/usr/src/app/backend
      - static_volume:/usr/src/app/backend/static
      - database_volume:/var/lib/postgresql/data
    entrypoint: /usr/src/app/backend/entrypoint.sh
    ports:
      - "5100:5100"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    depends_on:
      - backend
volumes:
  database_volume:
  static_volume: